### ISSUE TITLE
Help while installing jsm-editor

### ISSUE THREAD

**Issue by alphacodes26** [adrianhajdin/collaborative-editor#1]
env: ts-node: No such file or directory

**Comment by CodeSurgeonPritam** [comment]
why this  when install  and add 
npx jsm-editor add editor

env: ts-node: No such file or directoryd @adrianhajdin @sujatagunale

**Comment by sujatagunale** [comment]
@alphacodes26  and @pritamkumar143 install ts-node globally 

```bash
npm install -g ts-node
```

**Comment by VanstrahlenAlex** [comment]
Thanks for the help @sujatagunale

**Comment by bhavyamm01** [comment]
@sujatagunale Getting `env: ts-node\r: No such file or directory` even after installing `ts-node` globally

**Comment by Prince7reigns** [comment]
@bhavyamm01 its wroking

**Comment by lordwisetech** [comment]
thanks It work

**Comment by CodewithHassangithub** [comment]
> env: ts-node: No such file or directory

nom i ts-node
