### ISSUE TITLE
TypeError: (0 , _lib_actions_room_actions__WEBPACK_IMPORTED_MODULE_2__.getDocument) is not a function

### ISSUE THREAD

**Issue by alphacodes26** [adrianhajdin/collaborative-editor#2]
got this error 
<img width="975" alt="Screenshot 2024-07-20 at 1 17 58 PM" src="https://github.com/user-attachments/assets/bf69b281-9e7a-4ad0-9d01-763876882a88">

**Comment by Kaustav2410** [comment]
Did you fixed this error, if yes how so?
