### ISSUE TITLE
Editor page (Document) not rendering 

### ISSUE THREAD

**Issue by Madhannmady07** [adrianhajdin/collaborative-editor#5]
at the time stamp of 01:05:09, he told the reason why the page is not rendered is because of, the "Document Component" is not properly written, so he eventually fills the document .

But my issue is , even after doing the same ,what he does  , the page is not rendered for me , which means , " The issue is not resolved for me " and he then proceeds to code the next component and im now stuck at this component.

Please, someone guide  me through the process , and help to rectify this issue.

**Comment by Riteek712** [comment]
Hey was this fixed?? My useEditorStatus() is not getting updated
